:headline: About the Author
:body: |
  I'm [@danielrheath](https://twitter.com/#!/danielrheath) and I [write about tech occasionally](http://danielrheath.net/).
  I didn't create ActiveFacts but I do think it's pretty cool.
  Feel free to get in touch; I'm happy to chat about stuff.